language: python
cache:
  pip: true
  directories:
    - .mypy_cache
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

matrix:
  include:
    python: 3.7
    dist: xenial
    sudo: required

os:
  - linux

script: tox
install:
  - pip install tox-travis
notifications:
  email: false
