language: python
cache:
  pip: true
  directories:
    - .mypy_cache

os:
  - linux
jobs:
  include:
    - stage: test
      python: "2.7"
    - stage: test
      python: "3.4"
    - stage: test
      python: "3.5"
    - stage: test
      python: "3.6"
    - stage: test
      python: "3.7"
      dist: xenial
      sudo: required
    - stage: release-test
      script: RELEASE_SKIP=head PYVER= ./release-test.sh

script: tox
install:
  - pip install tox-travis
notifications:
  email: false
